version: '3.8'
services:
  mysql-master:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
    volumes:
      - master-data:/var/lib/mysql
    networks:
      - app-network

  mysql-slave-1:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
    volumes:
      - slave1-data:/var/lib/mysql
    networks:
      - app-network

  mysql-slave-2:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
    volumes:
      - slave2-data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    networks:
      - app-network

  mongodb:
    image: mongo:4.0
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  php:
    build: ./backend/php
    volumes:
      - ./backend/php:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app-network

  nodejs:
    build: ./backend/node
    volumes:
      - ./backend/node/src:/usr/src/app
    ports:
      - "3001:3000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/usr/src/app/src
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  master-data:
  slave1-data:
  slave2-data:
  mongo-data:

networks:
  app-network:
